### ISSUE TITLE
Hi, going to give this a shot :)

### ISSUE THREAD

**Issue by SeanScherer** [richbl/a-bash-template#4]
I was looking for a different project yesterday (unfortunately, no luck), but I reckon this will do me for starters (and still help a long way compared to setting my script up from scratch.

Just wanted to give you a shout out, I'll definitely let you know if I run into any trouble :P. (I'm a beginner bash programmer, so pretty likely maybe...).

Regards, Sean

**Comment by SeanScherer** [comment]
Ah, sorry to provide "negative" feedback so soon.. 

First though, I really like the idea of setting up the arguments as simple configs! 

( What I've not understood yet is whether / how you would set up mutually exclusive ones, eg choosing between "build", "pre-build", "run" or such).

The external dependency is what makes this a non-starter for me, cause the reason I was going to set up the script was to remove the dependency on python (sure, it'd be a smaller dependancy, but a dependency non the less..).

Still is interesting to see this approach :) !

**Comment by richbl** [comment]
@SeanScherer, I appreciate the feedback. Best of luck with your future bash scripting projects.

Yes, BaT has one dependency, `jq`, needed to parse the JSON file. In theory you _could_ build your own bash-based JSON parser which would alleviate this requirement ;). That said, `jq` is very lightweight.

Regarding the need for mutually exclusive parameter passing, I'm not sure I entirely understand the use case. Keep in mind that the argument flags set up in the JSON file can associate with them any string. So in your example, you could create an "action" parameter, make it required, and then parse the associated string, looking for "compile", "build", "run", etc. You can decide how to respond based on what gets passed via the "action" parameter. If you take a look at the `bash_template.sh` script, `ARG_ALPHA="$(get_config_arg_value alpha)"` makes the assignment of the parsed value found for the `alpha` argument. You'll see that the heavy lifting is parsing arguments: what you do with them is up to you.

**Comment by SeanScherer** [comment]
Thank you for the explanation - I think what you describe is exactly what I was asking about (but was non-obvious to me :P).

I'm sure I'll give this a shot then, even if its just to see if I can get it working as I intend :) !
